[package]
name = "hier-kv-gateway-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hier-kv-gateway-kv-estimate = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
xxhash-rust = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
toml = { workspace = true }
