//! OpenAI API-compatible request/response JSON types.
//!
//! This module defines an external JSON protocol consistent with the OpenAI Chat
//! Completions API, and provides bidirectional conversion with Hier KV Gateway's
//! internal [`hier_kv_gateway_core::request::InferenceRequest`]:
//!
//! - [`OpenAIChatRequest`]: Request body for client `POST /v1/chat/completions`.
//! - [`OpenAIChatResponse`]: Non-streaming response body, consistent with the OpenAI API.
//! - [`OpenAIChatChunk`]: A single chunk in a streaming SSE response.
//! - [`OpenAIModelList`]: Response body for `GET /v1/models`.
//!
//! The conversion function [`OpenAIChatRequest::to_inference_request`] generates a new
//! [`RequestId`], and flattens OpenAI-style `tools` (nested `function` field) into the
//! [`ToolDefinition`] used internally by Hier KV Gateway.

use serde::{Deserialize, Serialize};

use hier_kv_gateway_core::ids::RequestId;
use hier_kv_gateway_core::request::{ChatMessage, InferenceRequest, ToolDefinition};

/// Default sampling temperature, consistent with OpenAI.
const DEFAULT_TEMPERATURE: f64 = 1.0;
/// Default maximum number of generated tokens.
const DEFAULT_MAX_TOKENS: u32 = 1024;

/// OpenAI Chat Completions request body.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChatRequest {
    /// Target model name.
    pub model: String,
    /// List of chat messages.
    pub messages: Vec<OpenAIMessage>,
    /// Maximum number of generated tokens; defaults to [`DEFAULT_MAX_TOKENS`] when absent.
    #[serde(default = "default_max_tokens")]
    pub max_tokens: u32,
    /// Sampling temperature; defaults to [`DEFAULT_TEMPERATURE`] when absent.
    #[serde(default = "default_temperature")]
    pub temperature: f64,
    /// Whether streaming output is enabled.
    #[serde(default)]
    pub stream: bool,
    /// Available tool list (OpenAI-style `function` tools).
    #[serde(default)]
    pub tools: Vec<OpenAITool>,
    /// Optional LoRA adapter name (Hier KV Gateway extension field).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_name: Option<String>,
    /// Optional session ID, used for session-affinity routing (Hier KV Gateway extension field).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
    /// Optional pre-tokenized token sequence (Hier KV Gateway extension field, used for KV routing).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub token_ids: Vec<u32>,
}

fn default_temperature() -> f64 {
    DEFAULT_TEMPERATURE
}

fn default_max_tokens() -> u32 {
    DEFAULT_MAX_TOKENS
}

/// OpenAI-style chat message.
///
/// `content` only supports plain text, consistent with Hier KV Gateway's internal
/// [`ChatMessage`]; multimodal content (images, etc.) is not currently supported.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct OpenAIMessage {
    /// Role, e.g. `system`, `user`, `assistant`.
    pub role: String,
    /// Message text content.
    pub content: String,
}

/// OpenAI-style tool definition.
///
/// Serialized form:
/// ```json
/// { "type": "function", "function": { "name": "...", "description": "...", "parameters": {...} } }
/// ```
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAITool {
    /// Tool type; currently only `function` is supported.
    #[serde(rename = "type")]
    pub tool_type: String,
    /// Function definition.
    pub function: OpenAIToolFunction,
}

/// OpenAI-style tool function definition.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIToolFunction {
    /// Function name.
    pub name: String,
    /// Function description.
    #[serde(default)]
    pub description: String,
    /// Parameter JSON Schema (any JSON value).
    #[serde(default)]
    pub parameters: serde_json::Value,
}

/// OpenAI Chat Completions non-streaming response body.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChatResponse {
    /// Unique response ID (consistent with the request `id` or generated by the server).
    pub id: String,
    /// Object type, fixed to `"chat.completion"`.
    pub object: String,
    /// Creation timestamp (Unix seconds).
    pub created: i64,
    /// Model name used to generate this response.
    pub model: String,
    /// List of choices (non-streaming usually has only one).
    pub choices: Vec<OpenAIChoice>,
    /// Usage statistics.
    pub usage: OpenAIUsage,
}

/// A single choice in a non-streaming response.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChoice {
    /// Choice index.
    pub index: u32,
    /// Choice message.
    pub message: OpenAIChoiceMessage,
    /// Finish reason, e.g. `stop`, `length`, `tool_calls`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// Message in a non-streaming response.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChoiceMessage {
    /// Role, fixed to `assistant`.
    pub role: String,
    /// Text content.
    #[serde(default)]
    pub content: String,
}

/// Token usage statistics.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct OpenAIUsage {
    /// Number of prompt tokens.
    pub prompt_tokens: u64,
    /// Number of generated tokens.
    pub completion_tokens: u64,
    /// Total number of tokens.
    pub total_tokens: u64,
}

/// A single SSE chunk in an OpenAI Chat Completions streaming response.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChatChunk {
    /// Unique response ID.
    pub id: String,
    /// Object type, fixed to `"chat.completion.chunk"`.
    pub object: String,
    /// Creation timestamp (Unix seconds).
    pub created: i64,
    /// Model name used to generate this chunk.
    pub model: String,
    /// List of choices (streaming usually has only one).
    pub choices: Vec<OpenAIChunkChoice>,
}

/// A single choice in a streaming chunk.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIChunkChoice {
    /// Choice index.
    pub index: u32,
    /// Incremental delta.
    pub delta: OpenAIDelta,
    /// Finish reason, only present in the final chunk of the stream.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// Incremental content in a streaming chunk.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIDelta {
    /// Role, only present in the first chunk.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Incremental text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

/// Response body for `GET /v1/models`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIModelList {
    /// Object type, fixed to `"list"`.
    pub object: String,
    /// List of model entries.
    pub data: Vec<OpenAIModel>,
}

/// A single model entry.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OpenAIModel {
    /// Model ID.
    pub id: String,
    /// Object type, fixed to `"model"`.
    pub object: String,
    /// Creation timestamp (Unix seconds).
    pub created: i64,
    /// Model owner (OpenAI-compatible field; in Hier KV Gateway, filled with the backend identifier).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owned_by: Option<String>,
}

impl OpenAIChatRequest {
    /// Convert an OpenAI-style request into Hier KV Gateway's internal [`InferenceRequest`].
    ///
    /// - Automatically generates a new [`RequestId`] (based on UUID v4).
    /// - Maps [`OpenAIMessage`] to [`ChatMessage`].
    /// - Flattens [`OpenAITool`] into [`ToolDefinition`]; the `parameters` field is stored
    ///   as JSON text.
    pub fn to_inference_request(&self) -> InferenceRequest {
        let request_id = RequestId::new(uuid::Uuid::new_v4().to_string());
        let messages: Vec<ChatMessage> = self
            .messages
            .iter()
            .map(|m| ChatMessage {
                role: m.role.clone(),
                content: m.content.clone(),
            })
            .collect();
        let tools: Vec<ToolDefinition> = self
            .tools
            .iter()
            .map(|t| ToolDefinition {
                name: t.function.name.clone(),
                description: t.function.description.clone(),
                parameters_schema: serde_json::to_string(&t.function.parameters)
                    .unwrap_or_else(|_| "{}".to_string()),
            })
            .collect();
        InferenceRequest {
            request_id,
            model: self.model.clone(),
            messages,
            token_ids: self.token_ids.clone(),
            max_tokens: self.max_tokens,
            temperature: self.temperature,
            stream: self.stream,
            tools,
            lora_name: self.lora_name.clone(),
        }
    }
}

impl OpenAIChatResponse {
    /// Construct a non-streaming response from the request ID, model name, merged text
    /// content, and finish reason.
    ///
    /// `prompt_tokens` / `completion_tokens` are provided by the caller; `total_tokens`
    /// is summed automatically.
    pub fn from_text(
        request_id: &str,
        model: &str,
        content: String,
        finish_reason: Option<String>,
        prompt_tokens: u64,
        completion_tokens: u64,
    ) -> Self {
        let created = chrono::Utc::now().timestamp();
        Self {
            id: request_id.to_string(),
            object: "chat.completion".to_string(),
            created,
            model: model.to_string(),
            choices: vec![OpenAIChoice {
                index: 0,
                message: OpenAIChoiceMessage {
                    role: "assistant".to_string(),
                    content,
                },
                finish_reason,
            }],
            usage: OpenAIUsage {
                prompt_tokens,
                completion_tokens,
                total_tokens: prompt_tokens + completion_tokens,
            },
        }
    }
}

impl OpenAIChatChunk {
    /// Construct a streaming start chunk (carries `role: "assistant"`).
    pub fn role_chunk(request_id: &str, model: &str) -> Self {
        Self {
            id: request_id.to_string(),
            object: "chat.completion.chunk".to_string(),
            created: chrono::Utc::now().timestamp(),
            model: model.to_string(),
            choices: vec![OpenAIChunkChoice {
                index: 0,
                delta: OpenAIDelta {
                    role: Some("assistant".to_string()),
                    content: None,
                },
                finish_reason: None,
            }],
        }
    }

    /// Construct a chunk carrying incremental text.
    pub fn delta_chunk(request_id: &str, model: &str, content: String) -> Self {
        Self {
            id: request_id.to_string(),
            object: "chat.completion.chunk".to_string(),
            created: chrono::Utc::now().timestamp(),
            model: model.to_string(),
            choices: vec![OpenAIChunkChoice {
                index: 0,
                delta: OpenAIDelta {
                    role: None,
                    content: Some(content),
                },
                finish_reason: None,
            }],
        }
    }

    /// Construct the final chunk of the stream (carries `finish_reason`).
    pub fn finish_chunk(request_id: &str, model: &str, finish_reason: &str) -> Self {
        Self {
            id: request_id.to_string(),
            object: "chat.completion.chunk".to_string(),
            created: chrono::Utc::now().timestamp(),
            model: model.to_string(),
            choices: vec![OpenAIChunkChoice {
                index: 0,
                delta: OpenAIDelta {
                    role: None,
                    content: None,
                },
                finish_reason: Some(finish_reason.to_string()),
            }],
        }
    }
}

impl OpenAIModelList {
    /// Construct a model list response from a set of model IDs.
    pub fn from_model_ids<I>(into_iter: I) -> Self
    where
        I: IntoIterator<Item = (String, Option<String>)>,
    {
        let created = chrono::Utc::now().timestamp();
        let data: Vec<OpenAIModel> = into_iter
            .into_iter()
            .map(|(id, owned_by)| OpenAIModel {
                id,
                object: "model".to_string(),
                created,
                owned_by,
            })
            .collect();
        Self {
            object: "list".to_string(),
            data,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_openai_chat_request_minimal() {
        let s = r#"{
            "model": "gpt-4",
            "messages": [{"role":"user","content":"hi"}]
        }"#;
        let req: OpenAIChatRequest = serde_json::from_str(s).unwrap();
        assert_eq!(req.model, "gpt-4");
        assert_eq!(req.messages.len(), 1);
        assert!(!req.stream);
        assert!((req.temperature - 1.0).abs() < 1e-9);
        assert_eq!(req.max_tokens, DEFAULT_MAX_TOKENS);
    }

    #[test]
    fn parse_openai_chat_request_full() {
        let s = r#"{
            "model": "qwen2.5-7b",
            "messages": [{"role":"user","content":"hi"}],
            "max_tokens": 256,
            "temperature": 0.3,
            "stream": true,
            "tools": [
                {"type":"function","function":{"name":"f","description":"d","parameters":{"type":"object"}}}
            ],
            "lora_name": "adapter-a",
            "session": "sess-1",
            "token_ids": [1,2,3]
        }"#;
        let req: OpenAIChatRequest = serde_json::from_str(s).unwrap();
        assert!(req.stream);
        assert!((req.temperature - 0.3).abs() < 1e-9);
        assert_eq!(req.max_tokens, 256);
        assert_eq!(req.tools.len(), 1);
        assert_eq!(req.lora_name.as_deref(), Some("adapter-a"));
        assert_eq!(req.token_ids, vec![1, 2, 3]);
    }

    #[test]
    fn to_inference_request_maps_fields() {
        let req = OpenAIChatRequest {
            model: "m".to_string(),
            messages: vec![OpenAIMessage {
                role: "user".to_string(),
                content: "hello".to_string(),
            }],
            max_tokens: 64,
            temperature: 0.5,
            stream: true,
            tools: vec![OpenAITool {
                tool_type: "function".to_string(),
                function: OpenAIToolFunction {
                    name: "f".to_string(),
                    description: "d".to_string(),
                    parameters: serde_json::json!({"type": "object"}),
                },
            }],
            lora_name: Some("adapter".to_string()),
            session: Some("sess".to_string()),
            token_ids: vec![1, 2],
        };
        let infer = req.to_inference_request();
        assert_eq!(infer.model, "m");
        assert_eq!(infer.messages.len(), 1);
        assert_eq!(infer.max_tokens, 64);
        assert!((infer.temperature - 0.5).abs() < 1e-9);
        assert!(infer.stream);
        assert_eq!(infer.tools.len(), 1);
        assert_eq!(infer.tools[0].name, "f");
        assert_eq!(infer.lora_name.as_deref(), Some("adapter"));
        assert_eq!(infer.token_ids, vec![1, 2]);
        // request_id should be a non-empty UUID-form string
        assert!(!infer.request_id.as_str().is_empty());
    }

    #[test]
    fn openai_chat_response_serializes() {
        let resp = OpenAIChatResponse::from_text(
            "req-1",
            "m",
            "hello".to_string(),
            Some("stop".to_string()),
            5,
            3,
        );
        let s = serde_json::to_string(&resp).unwrap();
        assert!(s.contains("\"object\":\"chat.completion\""));
        assert!(s.contains("\"role\":\"assistant\""));
        assert!(s.contains("\"content\":\"hello\""));
        assert!(s.contains("\"finish_reason\":\"stop\""));
        assert!(s.contains("\"total_tokens\":8"));
    }

    #[test]
    fn openai_chat_chunk_role_chunk() {
        let chunk = OpenAIChatChunk::role_chunk("req-1", "m");
        assert_eq!(chunk.object, "chat.completion.chunk");
        assert_eq!(chunk.choices[0].delta.role.as_deref(), Some("assistant"));
        assert!(chunk.choices[0].delta.content.is_none());
    }

    #[test]
    fn openai_chat_chunk_delta_chunk() {
        let chunk = OpenAIChatChunk::delta_chunk("req-1", "m", "hi".to_string());
        assert_eq!(chunk.choices[0].delta.content.as_deref(), Some("hi"));
        assert!(chunk.choices[0].delta.role.is_none());
    }

    #[test]
    fn openai_chat_chunk_finish_chunk() {
        let chunk = OpenAIChatChunk::finish_chunk("req-1", "m", "stop");
        assert_eq!(
            chunk.choices[0].finish_reason.as_deref(),
            Some("stop")
        );
    }

    #[test]
    fn openai_model_list_from_ids() {
        let list = OpenAIModelList::from_model_ids(
            [("m1".to_string(), None), ("m2".to_string(), Some("backend-1".to_string()))],
        );
        assert_eq!(list.object, "list");
        assert_eq!(list.data.len(), 2);
        assert_eq!(list.data[0].id, "m1");
        assert_eq!(list.data[1].owned_by.as_deref(), Some("backend-1"));
    }
}
